on:
  push:
    branches: [experiment_gha_docs]
jobs:
  upload_to_nightlies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build docker image
        run: |
          docker build -t docs docs/docker
      - name: Build documentation
        run: |
          docker run  --rm --volume "$PWD:/root/flink" -it docs bash -c "cd /root/flink && ./docs/ci.sh"
      - name: Upload documentation
        run: |
          echo "success"