on:
  push:
    branches: [experiment_gha_docs]
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print current branch
        run: |
          currentBranch=$(git branch --show-current)
          echo "${currentBranch}"